version: "2.1"
services:
     webfrontend:
          build:
               context: .
               dockerfile: dev.dockerfile
          container_name: omsubmission
          volumes:
                - "./app:/app"
                - "./_data/db:/data/db"
          ports:
               - "9000:80"
               - "27017:27017"
               - "28017:28017"
