version: "2.1"
services:
     database:
          image: mongo
          container_name: mongodb
          volumes:
               - "./_data/db:/data/db"
          ports:
               - "27017:27017"
     webfrontend:
          build:
               context: .
               dockerfile: dev.dockerfile
          container_name: omsubmission
          environment:
               - NODE_DEV=false
               - MONGODB_ADDRESS=database
               - MONGODB_PORT=27017
          volumes:
                #- "./app:/app/public"
                - "./_data/db:/data/db"
          ports:
               - "9000:8080"
          links:
               - "database:db2"
